<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="PJeCalc.Core\PJeCalc.Core.csproj" />
    <ProjectReference Include="PJeCalc.Data\PJeCalc.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>PJE_Calc_Reborn</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PJeCalc.Core\**" />
    <Compile Remove="PJeCalc.Data\**" />
    <Compile Remove="PJeCalc.Tests\**" />
    <Compile Remove="decompiled\**" />
    <EmbeddedResource Remove="PJeCalc.Core\**" />
    <EmbeddedResource Remove="PJeCalc.Data\**" />
    <EmbeddedResource Remove="PJeCalc.Tests\**" />
    <EmbeddedResource Remove="decompiled\**" />
    <None Remove="PJeCalc.Core\**" />
    <None Remove="PJeCalc.Data\**" />
    <None Remove="PJeCalc.Tests\**" />
    <None Remove="decompiled\**" />
  </ItemGroup>

</Project>
