-- Extrai tabelas de referência do H2 do PJe-Calc para CSV (colunas normalizadas).
-- Diretório de saída: passado via caminho absoluto nos CALL abaixo.
-- Índices mensais: competencia, taxa
CALL CSVWRITE('OUTDIR/tr.csv',            'SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBTR ORDER BY DDTCOMPETENCIAINDICE');
CALL CSVWRITE('OUTDIR/ipcae.csv',         'SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBIPCAE ORDER BY DDTCOMPETENCIAINDICE');
CALL CSVWRITE('OUTDIR/ipcaetr.csv',       'SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBIPCAETR ORDER BY DDTCOMPETENCIAINDICE');
CALL CSVWRITE('OUTDIR/ipca.csv',          'SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBIPCA ORDER BY DDTCOMPETENCIAINDICE');
CALL CSVWRITE('OUTDIR/inpc.csv',          'SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBINPC ORDER BY DDTCOMPETENCIAINDICE');
CALL CSVWRITE('OUTDIR/igpm.csv',          'SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBIGPM ORDER BY DDTCOMPETENCIAINDICE');
CALL CSVWRITE('OUTDIR/ipc.csv',           'SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBIPC ORDER BY DDTCOMPETENCIAINDICE');
CALL CSVWRITE('OUTDIR/selicfazenda.csv',  'SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBSELICFAZENDA ORDER BY DDTCOMPETENCIAINDICE');
CALL CSVWRITE('OUTDIR/indebitotributario.csv','SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBINDEBITOTRIBUTARIO ORDER BY DDTCOMPETENCIAINDICE');
CALL CSVWRITE('OUTDIR/tabelaunicamensal.csv','SELECT DDTCOMPETENCIAINDICE AS competencia, RVLINDICE AS taxa FROM TBTABELAUNICAJTMENSAL ORDER BY DDTCOMPETENCIAINDICE');
-- Índices diários: dia, taxa
CALL CSVWRITE('OUTDIR/jam.csv',           'SELECT DDTDIAINDICE AS dia, RVLINDICE AS taxa FROM TBJAM ORDER BY DDTDIAINDICE');
CALL CSVWRITE('OUTDIR/selicdiaria.csv',   'SELECT DDTDIAINDICE AS dia, RVLINDICE AS taxa FROM TBSELICDIARIA ORDER BY DDTDIAINDICE');
CALL CSVWRITE('OUTDIR/tabelaunicadiaria.csv','SELECT DDTDIAINDICE AS dia, RVLINDICE AS taxa FROM TBTABELAUNICAJTDIARIA ORDER BY DDTDIAINDICE');
CALL CSVWRITE('OUTDIR/taxalegal.csv',     'SELECT DDTDIAINDICE AS dia, RVLINDICE AS taxa FROM TBJUROSTAXALEGAL ORDER BY DDTDIAINDICE');
-- Salário mínimo nacional: competencia, salario
CALL CSVWRITE('OUTDIR/salariominimo.csv', 'SELECT DDTCOMPETENCIA AS competencia, RVLSALARIO AS salario FROM TBSALARIOMINIMONACIONAL ORDER BY DDTCOMPETENCIA');
-- Juros por faixa: dataInicio, dataFim, taxa, tipoJuros, tipoQuantidade
CALL CSVWRITE('OUTDIR/jurospadrao.csv',       'SELECT DDTINICIO AS dataInicio, DDTFIM AS dataFim, RVLTAXA AS taxa, STPJUROS AS tipoJuros, STPQUANTIDADE AS tipoQuantidade FROM TBJUROSPADRAO ORDER BY DDTINICIO');
CALL CSVWRITE('OUTDIR/jurosfazendapublica.csv','SELECT DDTINICIO AS dataInicio, DDTFIM AS dataFim, RVLTAXA AS taxa, STPJUROS AS tipoJuros, STPQUANTIDADE AS tipoQuantidade FROM TBJUROSFAZENDAPUBLICA ORDER BY DDTINICIO');
-- Juros SELIC (INSS/IRPF): competencia, taxaSelic, competenciaReferencia
CALL CSVWRITE('OUTDIR/jurosselicinss.csv','SELECT DDTCOMPETENCIA AS competencia, RVLTAXASELIC AS taxaSelic, DDTCOMPETENCIAREFERENCIA AS competenciaReferencia FROM TBJUROSSELICINSS ORDER BY DDTCOMPETENCIA');
CALL CSVWRITE('OUTDIR/jurosselicirpf.csv','SELECT DDTCOMPETENCIA AS competencia, RVLTAXASELIC AS taxaSelic, DDTCOMPETENCIAREFERENCIA AS competenciaReferencia FROM TBJUROSSELICIRPF ORDER BY DDTCOMPETENCIA');
